# Functions



`BiblicalHebrew.codept`


:::{.callout-note appearance="minimal"}
```{julia}
#| echo: false
#| warning: false
using BiblicalHebrew
@doc BiblicalHebrew.codept
```
:::


`BiblicalHebrew.codept_name`


:::{.callout-note appearance="minimal"}
```{julia}
#| echo: false
#| warning: false
@doc BiblicalHebrew.codept_name
```
:::


BiblicalHebrew.codept_split


:::{.callout-note appearance="minimal"}
```{julia}
#| echo: false
#| warning: false
@doc BiblicalHebrew.codept_name
```
:::

BiblicalHebrew.dagesh


:::{.callout-note appearance="minimal"}
```{julia}
#| echo: false
#| warning: false
@doc BiblicalHebrew.codept_name
```
:::

BiblicalHebrew.gershe


:::{.callout-note appearance="minimal"}
```{julia}
#| echo: false
#| warning: false
@doc BiblicalHebrew.codept_name
```
:::



BiblicalHebrew.has_sheva


:::{.callout-note appearance="minimal"}
```{julia}
#| echo: false
#| warning: false
@doc BiblicalHebrew.codept_name
```
:::



BiblicalHebrew.has_vowelpoint


:::{.callout-note appearance="minimal"}
```{julia}
#| echo: false
#| warning: false
@doc BiblicalHebrew.codept_name
```
:::



BiblicalHebrew.hebrew_chars


:::{.callout-note appearance="minimal"}
```{julia}
#| echo: false
#| warning: false
@doc BiblicalHebrew.codept_name
```
:::


BiblicalHebrew.hex


:::{.callout-note appearance="minimal"}
```{julia}
#| echo: false
#| warning: false
@doc BiblicalHebrew.codept_name
```
:::


BiblicalHebrew.hiriq


:::{.callout-note appearance="minimal"}
```{julia}
#| echo: false
#| warning: false
@doc BiblicalHebrew.codept_name
```
:::


BiblicalHebrew.holam


:::{.callout-note appearance="minimal"}
```{julia}
#| echo: false
#| warning: false
@doc BiblicalHebrew.codept_name
```
:::


BiblicalHebrew.int


:::{.callout-note appearance="minimal"}
```{julia}
#| echo: false
#| warning: false
@doc BiblicalHebrew.codept_name
```
:::


BiblicalHebrew.is_alphabetic


:::{.callout-note appearance="minimal"}
```{julia}
#| echo: false
#| warning: false
@doc BiblicalHebrew.codept_name
```
:::


BiblicalHebrew.is_begadkepat



:::{.callout-note appearance="minimal"}
```{julia}
#| echo: false
#| warning: false
@doc BiblicalHebrew.codept_name
```
:::



BiblicalHebrew.is_consonant



:::{.callout-note appearance="minimal"}
```{julia}
#| echo: false
#| warning: false
@doc BiblicalHebrew.codept_name
```
:::




BiblicalHebrew.is_guttural



:::{.callout-note appearance="minimal"}
```{julia}
#| echo: false
#| warning: false
@doc BiblicalHebrew.codept_name
```
:::



BiblicalHebrew.is_long



:::{.callout-note appearance="minimal"}
```{julia}
#| echo: false
#| warning: false
@doc BiblicalHebrew.codept_name
```
:::



BiblicalHebrew.is_mater



:::{.callout-note appearance="minimal"}
```{julia}
#| echo: false
#| warning: false
@doc BiblicalHebrew.codept_name
```
:::



BiblicalHebrew.is_vowelpoint



:::{.callout-note appearance="minimal"}
```{julia}
#| echo: false
#| warning: false
@doc BiblicalHebrew.codept_name
```
:::



BiblicalHebrew.mappiq



:::{.callout-note appearance="minimal"}
```{julia}
#| echo: false
#| warning: false
@doc BiblicalHebrew.codept_name
```
:::



BiblicalHebrew.maqaf_join


:::{.callout-note appearance="minimal"}
```{julia}
#| echo: false
#| warning: false
@doc BiblicalHebrew.codept_name
```
:::

BiblicalHebrew.metheg


:::{.callout-note appearance="minimal"}
```{julia}
#| echo: false
#| warning: false
@doc BiblicalHebrew.codept_name
```
:::

BiblicalHebrew.ole


:::{.callout-note appearance="minimal"}
```{julia}
#| echo: false
#| warning: false
@doc BiblicalHebrew.codept_name
```
:::

BiblicalHebrew.patah


:::{.callout-note appearance="minimal"}
```{julia}
#| echo: false
#| warning: false
@doc BiblicalHebrew.codept_name
```
:::

BiblicalHebrew.qamats


:::{.callout-note appearance="minimal"}
```{julia}
#| echo: false
#| warning: false
@doc BiblicalHebrew.codept_name
```
:::

BiblicalHebrew.qubbuts


:::{.callout-note appearance="minimal"}
```{julia}
#| echo: false
#| warning: false
@doc BiblicalHebrew.codept_name
```
:::

BiblicalHebrew.reduced_vowel


:::{.callout-note appearance="minimal"}
```{julia}
#| echo: false
#| warning: false
@doc BiblicalHebrew.codept_name
```
:::

BiblicalHebrew.rm_accents


:::{.callout-note appearance="minimal"}
```{julia}
#| echo: false
#| warning: false
@doc BiblicalHebrew.codept_name
```
:::

BiblicalHebrew.seghol


:::{.callout-note appearance="minimal"}
```{julia}
#| echo: false
#| warning: false
@doc BiblicalHebrew.codept_name
```
:::

BiblicalHebrew.sheva


:::{.callout-note appearance="minimal"}
```{julia}
#| echo: false
#| warning: false
@doc BiblicalHebrew.codept_name
```
:::

BiblicalHebrew.syllabify


:::{.callout-note appearance="minimal"}
```{julia}
#| echo: false
#| warning: false
@doc BiblicalHebrew.codept_name
```
:::

BiblicalHebrew.tokenize_string


:::{.callout-note appearance="minimal"}
```{julia}
#| echo: false
#| warning: false
@doc BiblicalHebrew.codept_name
```
:::

BiblicalHebrew.tsere


:::{.callout-note appearance="minimal"}
```{julia}
#| echo: false
#| warning: false
@doc BiblicalHebrew.codept_name
```
:::

BiblicalHebrew.unpointed


:::{.callout-note appearance="minimal"}
```{julia}
#| echo: false
#| warning: false
@doc BiblicalHebrew.codept_name
```
:::

BiblicalHebrew.validcps


:::{.callout-note appearance="minimal"}
```{julia}
#| echo: false
#| warning: false
@doc BiblicalHebrew.codept_name
```
:::

BiblicalHebrew.ws_chars


## Why are all these doc broken?

:::{.callout-note appearance="minimal"}
```{julia}
#| echo: false
#| warning: false
@doc BiblicalHebrew.codept_name
```
:::

`codepoints`


:::{.callout-note appearance="minimal"}
```{julia}
#| echo: false
#| warning: false
@doc codepoints
```
:::

`tokenize`


:::{.callout-note appearance="minimal"}
```{julia}
#| echo: false
#| warning: false
@doc tokenize
```
:::

`tokentypes`


:::{.callout-note appearance="minimal"}
```{julia}
#| echo: false
#| warning: false
@doc tokentypes
```
:::

`validstring`


:::{.callout-note appearance="minimal"}
```{julia}
#| echo: false
#| warning: false
@doc validstring
```
:::
